# -- Logging properties --
# logging.file.name: spring-app-sample.log

app.scheduler.enabled: false

server.port: 9000

spring:
    # file-size config
    servlet.multipart:
        max-file-size: 512KB
        max-request-size: 5120KB